// supabase/functions/_shared/foodPlaybook.ts
//
// EDGE-FUNCTION MIRROR of src/data/foodPlaybook.ts.
// Edit BOTH files in sync — same TypeScript content, just different
// runtime context (Deno edge function vs. Vite client bundle).
//
// CauseHealth's Food Playbook — curated library of brand-specific, hack-style
// meals across 12 playbooks. The edge function filters this library by user
// life_context (work, kids, cooking time, budget, eat-out chains, lunch/breakfast/dinner
// patterns) + lab targets (high TG, high ALT, low ferritin, etc.) and sends the
// top ~30 candidates to the AI. The AI picks 12-18 final meals and writes the
// lab-specific "why" text per user.
//
// Universal rule (locked in): no condition-specific hardcoding. Every meal works
// for any patient with the matching life_context. The AI's "why" is what ties
// each meal to the user's specific labs/symptoms.
//
// Adding new entries: keep names brand-specific, ingredients terse, targets[]
// describing what labs/symptoms the meal HELPS (the AI will use these to score
// matches). Constraints describe who SHOULDN'T see this meal.

export type Playbook =
  | 'convenience_store'
  | 'fast_food'
  | 'protein_bar_shake'
  | 'crock_pot'
  | 'sheet_pan'
  | 'frozen_aisle'
  | 'frozen_breakfast'
  | 'low_cal_drink'
  | 'mom_friendly'
  | 'viral_hack'
  | 'lunchbox_thermos'
  | 'simple_home_cook';

export type MealSlot = 'breakfast' | 'lunch' | 'dinner' | 'snack';
export type Phase = 1 | 2 | 3;
export type CostTier = 1 | 2 | 3; // 1 = cheap (<$5), 2 = mid ($5-12), 3 = higher ($12+)

// Lab/symptom targets a meal helps. AI ranks by how many user-specific
// targets the meal hits. Keywords are matched against user's lab flags
// + symptoms by the selector.
export type Target =
  | 'high_tg' | 'high_ldl' | 'high_apob' | 'high_chol' | 'low_hdl'
  | 'high_alt' | 'high_ast' | 'liver_stress'
  | 'high_glucose' | 'high_a1c' | 'insulin_resistance'
  | 'low_ferritin' | 'low_iron' | 'hair_loss'
  | 'low_b12' | 'low_folate' | 'brain_fog'
  | 'low_vitamin_d' | 'low_test'
  | 'gut_inflammation' | 'ibd_friendly' | 'low_fodmap'
  | 'high_protein' | 'low_carb' | 'high_fiber' | 'omega3'
  | 'sleep_support' | 'cortisol_calm' | 'energy_steady'
  | 'weight_loss' | 'muscle_gain' | 'satiety'
  | 'anti_inflammatory';

export interface MealConstraint {
  workType?: string[];           // restrict to these work_types
  excludeWorkType?: string[];    // exclude these work_types
  hasKids?: boolean;             // only show if user has kids
  noKids?: boolean;              // only show if no kids
  maxPrepMinutes?: number;       // user's cookingTimeAvailable must allow this
  minBudgetTier?: CostTier;      // user's budget must be at least this tier
  requiresChain?: string[];      // user must list at least one of these chains
  diet?: string[];               // works for these diets (vegan/keto/etc)
  excludeDiet?: string[];        // doesn't work for these diets
}

export interface MealEntry {
  id: string;                    // stable ID (slug-style)
  name: string;                  // brand-specific name (mandatory)
  emoji: string;
  playbook: Playbook;
  when: MealSlot;
  phase: Phase;                  // 1=Start Here, 2=Level Up, 3=Optimal
  ingredients: string[];         // short, brand-specific
  prepMinutes: number;
  cost: CostTier;
  protein_g?: number;            // approximate protein per serving
  targets: Target[];             // what labs/symptoms this helps
  constraint?: MealConstraint;
}

// ─────────────────────────────────────────────────────────────────────────────
// LIBRARY — 100+ entries, organized by playbook
// ─────────────────────────────────────────────────────────────────────────────

export const FOOD_PLAYBOOK: MealEntry[] = [
  // ── CONVENIENCE STORE GRABS ─────────────────────────────────────────────
  { id: 'wawa-egg-white-wrap', name: 'Wawa egg white wrap (chicken + spinach + cheese + corn salsa)', emoji: '🌯', playbook: 'convenience_store', when: 'breakfast', phase: 1, ingredients: ['Wawa egg white wrap', 'grilled chicken', 'spinach', 'cheese', 'corn salsa', 'black coffee'], prepMinutes: 0, cost: 2, protein_g: 30, targets: ['high_protein', 'low_folate', 'energy_steady'], constraint: { requiresChain: ['Wawa'] } },
  { id: 'wawa-turkey-hoagie', name: 'Wawa turkey hoagie short (mayo + mustard, regular cheese) + side salad', emoji: '🥖', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Wawa turkey hoagie short', 'mayo', 'mustard', 'cheese', 'lettuce', 'tomato', 'side salad', 'water or Diet Coke'], prepMinutes: 0, cost: 2, protein_g: 25, targets: ['high_protein', 'satiety'], constraint: { requiresChain: ['Wawa'] } },
  { id: 'wawa-tuna-hoagie', name: 'Wawa tuna hoagie on wheat short', emoji: '🐟', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Wawa tuna hoagie short', 'wheat roll', 'lettuce', 'tomato', 'pickles'], prepMinutes: 0, cost: 2, protein_g: 22, targets: ['high_protein', 'omega3', 'high_tg'], constraint: { requiresChain: ['Wawa'], excludeDiet: ['vegan', 'vegetarian'] } },
  { id: 'wawa-breakfast-quesadilla', name: 'Wawa breakfast quesadilla (chicken + cheese + egg)', emoji: '🫓', playbook: 'convenience_store', when: 'breakfast', phase: 1, ingredients: ['Wawa breakfast quesadilla', 'chicken', 'cheese', 'egg', 'salsa'], prepMinutes: 0, cost: 2, protein_g: 28, targets: ['high_protein', 'energy_steady'], constraint: { requiresChain: ['Wawa'] } },
  { id: '7eleven-big-bite-combo', name: '7-Eleven Big Bite combo: chicken Caesar wrap + Premier Protein shake', emoji: '🌯', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['7-Eleven chicken Caesar wrap', 'Premier Protein shake'], prepMinutes: 0, cost: 2, protein_g: 45, targets: ['high_protein', 'satiety'], constraint: { requiresChain: ['7-Eleven'] } },
  { id: '7eleven-cheese-cracker-combo', name: '7-Eleven Cheese & Crackers + 2× hard-boiled egg pack + apple', emoji: '🧀', playbook: 'convenience_store', when: 'snack', phase: 1, ingredients: ['cheese & crackers', '2× hard-boiled eggs', 'apple'], prepMinutes: 0, cost: 1, protein_g: 22, targets: ['high_protein', 'satiety'], constraint: { requiresChain: ['7-Eleven'] } },
  { id: 'sheetz-mto-flatbread', name: 'Sheetz MTO turkey flatbread (double meat, regular dressing, lettuce + tomato)', emoji: '🌯', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Sheetz turkey flatbread', 'double meat', 'lettuce', 'tomato', 'cheese', 'dressing'], prepMinutes: 0, cost: 2, protein_g: 35, targets: ['high_protein'], constraint: { requiresChain: ['Sheetz'] } },
  { id: 'sheetz-greek-salad', name: 'Sheetz Made-To-Order Greek salad with grilled chicken', emoji: '🥗', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Sheetz Greek salad', 'grilled chicken', 'feta', 'olives', 'tomato', 'cucumber', 'olive oil dressing'], prepMinutes: 0, cost: 2, protein_g: 35, targets: ['high_protein', 'low_carb', 'anti_inflammatory'], constraint: { requiresChain: ['Sheetz'] } },
  { id: 'truck-stop-protein-combo', name: 'Truck-stop protein box: 2-pack hard-boiled eggs + string cheese + apple + jerky stick', emoji: '🥚', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['2× hard-boiled eggs', 'string cheese', 'apple', 'jerky stick'], prepMinutes: 0, cost: 1, protein_g: 35, targets: ['high_protein', 'satiety'], constraint: { workType: ['driver', 'shift', 'labor'] } },
  { id: 'cumberland-farmhouse-sandwich', name: 'Cumberland Farms farmhouse breakfast sandwich + black coffee', emoji: '🥐', playbook: 'convenience_store', when: 'breakfast', phase: 1, ingredients: ['Cumberland Farms breakfast sandwich', 'black coffee'], prepMinutes: 0, cost: 1, protein_g: 18, targets: ['high_protein'], constraint: { requiresChain: ['Cumberland'] } },
  { id: 'gas-station-rescue', name: 'Gas-station rescue: granola bar + hard-boiled egg + cheese stick', emoji: '🥚', playbook: 'convenience_store', when: 'breakfast', phase: 1, ingredients: ['granola bar', 'hard-boiled egg', 'cheese stick'], prepMinutes: 0, cost: 1, protein_g: 25, targets: ['high_protein', 'satiety'] },
  { id: 'pilot-loves-rotisserie', name: 'Pilot/Love\'s truck stop: hot-case rotisserie chicken + bag of nuts + banana', emoji: '🍗', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['rotisserie chicken (hot case)', 'mixed nuts', 'banana'], prepMinutes: 0, cost: 2, protein_g: 40, targets: ['high_protein', 'satiety'], constraint: { workType: ['driver', 'shift'] } },
  // ── More Wawa variety (full daypart) ──
  { id: 'wawa-sizzli-bacon-egg-cheese', name: 'Wawa Sizzli bacon, egg & cheese on a pretzel bun + black coffee', emoji: '🥓', playbook: 'convenience_store', when: 'breakfast', phase: 1, ingredients: ['Wawa Sizzli bacon egg cheese pretzel bun', 'black coffee'], prepMinutes: 0, cost: 1, protein_g: 22, targets: ['high_protein'], constraint: { requiresChain: ['Wawa'] } },
  { id: 'wawa-bowls-buffalo-chicken', name: 'Wawa Bowls: buffalo chicken with grain blend + side salad', emoji: '🥣', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Wawa buffalo chicken bowl', 'grain blend', 'side salad'], prepMinutes: 0, cost: 2, protein_g: 32, targets: ['high_protein', 'high_fiber'], constraint: { requiresChain: ['Wawa'] } },
  { id: 'wawa-cheesesteak-short', name: 'Wawa cheesesteak short (chicken or steak) — split into 2 meals', emoji: '🥖', playbook: 'convenience_store', when: 'lunch', phase: 2, ingredients: ['Wawa chicken or steak cheesesteak short', 'lettuce', 'tomato', 'mayo'], prepMinutes: 0, cost: 2, protein_g: 28, targets: ['high_protein', 'satiety'], constraint: { requiresChain: ['Wawa'] } },
  { id: 'wawa-yogurt-parfait-egg-bites', name: 'Wawa yogurt parfait + egg bites (2-pack) + black coffee', emoji: '🥣', playbook: 'convenience_store', when: 'breakfast', phase: 1, ingredients: ['Wawa yogurt parfait', 'Wawa egg bites 2-pack', 'black coffee'], prepMinutes: 0, cost: 2, protein_g: 28, targets: ['high_protein'], constraint: { requiresChain: ['Wawa'] } },
  { id: 'wawa-cheese-jerky-apple', name: 'Wawa cheese cubes + beef jerky stick + apple', emoji: '🧀', playbook: 'convenience_store', when: 'snack', phase: 1, ingredients: ['Wawa cheese cubes', 'beef jerky stick', 'apple'], prepMinutes: 0, cost: 1, protein_g: 22, targets: ['high_protein', 'satiety'], constraint: { requiresChain: ['Wawa'] } },
  // ── More 7-Eleven ──
  { id: '7eleven-protein-pack-jerky', name: '7-Eleven protein pack: jerky + string cheese + hard-boiled egg + apple', emoji: '🥚', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['beef or turkey jerky', 'string cheese', 'hard-boiled egg', 'apple'], prepMinutes: 0, cost: 1, protein_g: 30, targets: ['high_protein'], constraint: { requiresChain: ['7-Eleven'] } },
  { id: '7eleven-tornado-eggs-coffee', name: '7-Eleven roller-grill chicken tornado + 2-pack hard-boiled eggs + black coffee', emoji: '🌯', playbook: 'convenience_store', when: 'breakfast', phase: 2, ingredients: ['7-Eleven chicken tornado', '2× hard-boiled eggs', 'black coffee'], prepMinutes: 0, cost: 1, protein_g: 28, targets: ['high_protein'], constraint: { requiresChain: ['7-Eleven'] } },
  { id: '7eleven-greek-yogurt-cup-bar', name: '7-Eleven Greek yogurt cup + Quest bar (grab + go)', emoji: '🥄', playbook: 'convenience_store', when: 'breakfast', phase: 1, ingredients: ['Greek yogurt cup', 'Quest bar'], prepMinutes: 0, cost: 1, protein_g: 28, targets: ['high_protein'], constraint: { requiresChain: ['7-Eleven'] } },
  { id: '7eleven-rolling-buffalo-wrap', name: '7-Eleven buffalo chicken roller wrap + Diet Coke', emoji: '🌶️', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['7-Eleven buffalo chicken wrap', 'Diet Coke'], prepMinutes: 0, cost: 1, protein_g: 22, targets: ['high_protein'], constraint: { requiresChain: ['7-Eleven'] } },
  // ── Sheetz extras ──
  { id: 'sheetz-shmuffin-egg-sausage', name: 'Sheetz Shmuffin egg + sausage + cheese on English muffin + black coffee', emoji: '🥚', playbook: 'convenience_store', when: 'breakfast', phase: 1, ingredients: ['Sheetz Shmuffin egg sausage cheese', 'black coffee'], prepMinutes: 0, cost: 1, protein_g: 20, targets: ['high_protein'], constraint: { requiresChain: ['Sheetz'] } },
  { id: 'sheetz-jr-meal-grilled', name: 'Sheetz junior meal: grilled chicken sandwich + side salad', emoji: '🥪', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Sheetz grilled chicken sandwich', 'side salad'], prepMinutes: 0, cost: 1, protein_g: 28, targets: ['high_protein'], constraint: { requiresChain: ['Sheetz'] } },

  // ── FAST-FOOD SMART ORDERS ──────────────────────────────────────────────
  { id: 'cfa-2x-grilled', name: '2× Chick-fil-A grilled chicken sandwiches + side salad', emoji: '🥪', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['2× Chick-fil-A grilled chicken sandwich', 'side salad', 'lite vinaigrette'], prepMinutes: 0, cost: 2, protein_g: 60, targets: ['high_protein', 'satiety', 'high_tg'], constraint: { requiresChain: ['Chick-fil-A'] } },
  { id: 'cfa-grilled-nuggets', name: 'Chick-fil-A grilled nuggets (12-pc) + side salad + diet lemonade', emoji: '🍗', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Chick-fil-A grilled nuggets 12pc', 'side salad', 'diet lemonade'], prepMinutes: 0, cost: 2, protein_g: 38, targets: ['high_protein', 'low_carb'], constraint: { requiresChain: ['Chick-fil-A'] } },
  { id: 'wendys-grilled-baked', name: 'Wendy\'s grilled chicken sandwich + baked potato + side salad', emoji: '🍔', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Wendy\'s grilled chicken sandwich', 'baked potato', 'side salad'], prepMinutes: 0, cost: 2, protein_g: 35, targets: ['high_protein', 'satiety'], constraint: { requiresChain: ['Wendy\'s'] } },
  { id: 'wendys-apple-pecan', name: 'Wendy\'s Apple Pecan Chicken Salad (full size)', emoji: '🥗', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Wendy\'s apple pecan chicken salad', 'pomegranate vinaigrette'], prepMinutes: 0, cost: 2, protein_g: 35, targets: ['high_protein', 'omega3'], constraint: { requiresChain: ['Wendy\'s'] } },
  { id: 'mcd-2x-egg-mcmuffin', name: 'McDonald\'s: 2× Egg McMuffin + black coffee', emoji: '🥚', playbook: 'fast_food', when: 'breakfast', phase: 1, ingredients: ['2× Egg McMuffin', 'black coffee'], prepMinutes: 0, cost: 2, protein_g: 36, targets: ['high_protein', 'satiety'], constraint: { requiresChain: ["McDonald's"] } },
  { id: 'mcd-mcnuggets-salad', name: 'McDonald\'s 4-pc Chicken McNuggets + side salad + apple slices', emoji: '🍗', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['McDonald\'s 4pc McNuggets', 'side salad', 'apple slices'], prepMinutes: 0, cost: 1, protein_g: 16, targets: ['high_protein'], constraint: { requiresChain: ["McDonald's"] } },
  { id: 'subway-rotisserie-flatbread', name: 'Subway rotisserie chicken on flatbread (double meat, all veggies)', emoji: '🥖', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Subway rotisserie chicken', 'flatbread', 'double meat', 'lettuce', 'tomato', 'spinach', 'olives', 'oil + vinegar'], prepMinutes: 0, cost: 2, protein_g: 40, targets: ['high_protein', 'high_fiber'], constraint: { requiresChain: ['Subway'] } },
  { id: 'subway-protein-bowl', name: 'Subway Protein Bowl (no bread, double meat, full veggies, dressing)', emoji: '🥗', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Subway protein bowl', 'double meat', 'all veggies', 'dressing'], prepMinutes: 0, cost: 2, protein_g: 45, targets: ['high_protein', 'low_carb'], constraint: { requiresChain: ['Subway'] } },
  { id: 'dunkin-2x-wakeup-wrap', name: 'Dunkin: 2× wake-up wraps + black coffee', emoji: '🌯', playbook: 'fast_food', when: 'breakfast', phase: 1, ingredients: ['2× Dunkin wake-up wrap', 'black coffee'], prepMinutes: 0, cost: 2, protein_g: 24, targets: ['high_protein'], constraint: { requiresChain: ['Dunkin'] } },
  { id: 'dunkin-bacon-egg-flatbread', name: 'Dunkin bacon + egg + cheese on multigrain flatbread + cold brew', emoji: '🥪', playbook: 'fast_food', when: 'breakfast', phase: 1, ingredients: ['Dunkin bacon egg cheese flatbread', 'multigrain', 'cold brew'], prepMinutes: 0, cost: 2, protein_g: 18, targets: ['high_protein'], constraint: { requiresChain: ['Dunkin'] } },
  { id: 'panera-power-chicken-hummus', name: 'Panera Power Chicken Hummus Bowl', emoji: '🥗', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Panera power chicken hummus bowl', 'chicken', 'hummus', 'tomato', 'cucumber'], prepMinutes: 0, cost: 2, protein_g: 35, targets: ['high_protein', 'high_fiber', 'satiety'], constraint: { requiresChain: ['Panera'] } },
  { id: 'panera-turkey-avocado', name: 'Panera Turkey Avocado BLT on whole grain (half order)', emoji: '🥪', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Panera turkey avocado BLT half', 'whole grain bread'], prepMinutes: 0, cost: 2, protein_g: 25, targets: ['high_protein'], constraint: { requiresChain: ['Panera'] } },
  { id: 'taco-bell-soft-tacos-supreme', name: 'Taco Bell: 2× Soft Taco Supreme (steak) + side of black beans', emoji: '🌮', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['2× Taco Bell soft taco supreme steak', 'side black beans'], prepMinutes: 0, cost: 1, protein_g: 28, targets: ['high_protein'], constraint: { requiresChain: ['Taco Bell'] } },
  { id: 'taco-bell-power-bowl', name: 'Taco Bell Power Menu Chicken Bowl', emoji: '🌯', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Taco Bell power menu chicken bowl', 'rice', 'black beans', 'lettuce', 'avocado ranch'], prepMinutes: 0, cost: 1, protein_g: 26, targets: ['high_protein', 'satiety'], constraint: { requiresChain: ['Taco Bell'] } },
  { id: 'bk-grilled-chicken', name: 'Burger King grilled chicken sandwich + side salad', emoji: '🍔', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['BK grilled chicken sandwich', 'side salad'], prepMinutes: 0, cost: 2, protein_g: 32, targets: ['high_protein'], constraint: { requiresChain: ['Burger King'] } },
  { id: 'chipotle-double-chicken-bowl', name: 'Chipotle bowl: double chicken, brown rice, fajita veggies, salsa, guac', emoji: '🍚', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Chipotle bowl', 'double chicken', 'brown rice', 'fajita peppers + onions', 'salsa', 'guac'], prepMinutes: 0, cost: 2, protein_g: 65, targets: ['high_protein', 'high_fiber', 'satiety', 'high_tg'], constraint: { requiresChain: ['Chipotle'] } },
  { id: 'five-guys-little-burger-salad', name: 'Five Guys little hamburger + side salad (no fries)', emoji: '🍔', playbook: 'fast_food', when: 'lunch', phase: 2, ingredients: ['Five Guys little hamburger', 'side salad'], prepMinutes: 0, cost: 2, protein_g: 22, targets: ['satiety'], constraint: { requiresChain: ['Five Guys'] } },
  { id: 'starbucks-protein-box', name: 'Starbucks protein box + iced black coffee', emoji: '🥚', playbook: 'fast_food', when: 'breakfast', phase: 1, ingredients: ['Starbucks protein box', 'iced black coffee'], prepMinutes: 0, cost: 2, protein_g: 23, targets: ['high_protein'], constraint: { requiresChain: ['Starbucks'] } },
  { id: 'cracker-barrel-grilled-chicken', name: 'Cracker Barrel grilled chicken + green beans + side salad', emoji: '🍗', playbook: 'fast_food', when: 'dinner', phase: 1, ingredients: ['Cracker Barrel grilled chicken', 'green beans', 'side salad'], prepMinutes: 0, cost: 2, protein_g: 40, targets: ['high_protein', 'low_carb'], constraint: { requiresChain: ['Cracker Barrel'] } },
  { id: 'olive-garden-chicken-parm', name: 'Olive Garden grilled chicken parmesan (eat the chicken, not the breading)', emoji: '🍝', playbook: 'fast_food', when: 'dinner', phase: 2, ingredients: ['Olive Garden grilled chicken parmesan', 'side salad', 'eat half the pasta'], prepMinutes: 0, cost: 3, protein_g: 45, targets: ['high_protein'], constraint: { requiresChain: ['Olive Garden'] } },

  // ── PROTEIN BARS + SHAKES ───────────────────────────────────────────────
  { id: 'kirkland-protein-bar', name: 'Costco Kirkland protein bar + apple', emoji: '🍫', playbook: 'protein_bar_shake', when: 'snack', phase: 1, ingredients: ['Kirkland protein bar', 'apple'], prepMinutes: 0, cost: 1, protein_g: 32, targets: ['high_protein', 'satiety'] },
  { id: 'premier-shake-vanilla', name: 'Premier Protein shake (vanilla) + handful of almonds', emoji: '🥛', playbook: 'protein_bar_shake', when: 'breakfast', phase: 1, ingredients: ['Premier Protein shake vanilla', 'almonds'], prepMinutes: 0, cost: 1, protein_g: 38, targets: ['high_protein', 'satiety'] },
  { id: 'quest-bar-apple', name: 'Quest bar (any flavor) + apple', emoji: '🍎', playbook: 'protein_bar_shake', when: 'breakfast', phase: 1, ingredients: ['Quest bar', 'apple'], prepMinutes: 0, cost: 1, protein_g: 22, targets: ['high_protein', 'satiety'] },
  { id: 'built-bar', name: 'Built Bar + black coffee (lower calorie viral pick)', emoji: '🍫', playbook: 'protein_bar_shake', when: 'snack', phase: 1, ingredients: ['Built Bar', 'black coffee'], prepMinutes: 0, cost: 1, protein_g: 17, targets: ['high_protein', 'weight_loss'] },
  { id: 'barebells-bar', name: 'Barebells protein bar (no chalky aftertaste)', emoji: '🍫', playbook: 'protein_bar_shake', when: 'snack', phase: 1, ingredients: ['Barebells protein bar'], prepMinutes: 0, cost: 1, protein_g: 20, targets: ['high_protein'] },
  { id: 'fairlife-shake', name: 'Fairlife Core Power protein milk + Quest bar', emoji: '🥛', playbook: 'protein_bar_shake', when: 'snack', phase: 1, ingredients: ['Fairlife Core Power', 'Quest bar'], prepMinutes: 0, cost: 2, protein_g: 48, targets: ['high_protein', 'muscle_gain'] },
  { id: 'desperate-stack', name: 'Desperate-day stack: Quest bar + Premier shake', emoji: '⚡', playbook: 'protein_bar_shake', when: 'lunch', phase: 1, ingredients: ['Quest bar', 'Premier Protein shake'], prepMinutes: 0, cost: 2, protein_g: 52, targets: ['high_protein', 'satiety'] },
  { id: 'owyn-shake', name: 'OWYN dairy-free shake (allergen-friendly)', emoji: '🥛', playbook: 'protein_bar_shake', when: 'snack', phase: 1, ingredients: ['OWYN shake'], prepMinutes: 0, cost: 1, protein_g: 20, targets: ['high_protein'], constraint: { diet: ['vegan', 'plant_based'] } },
  { id: 'ratio-yogurt-cup', name: 'Ratio yogurt cup + handful of berries', emoji: '🍓', playbook: 'protein_bar_shake', when: 'breakfast', phase: 1, ingredients: ['Ratio yogurt cup', 'fresh berries'], prepMinutes: 0, cost: 1, protein_g: 17, targets: ['high_protein'] },
  { id: 'two-good-yogurt', name: 'Two Good 80-cal yogurt + Kirkland protein bar', emoji: '🥄', playbook: 'protein_bar_shake', when: 'breakfast', phase: 1, ingredients: ['Two Good yogurt', 'Kirkland protein bar'], prepMinutes: 0, cost: 1, protein_g: 42, targets: ['high_protein', 'weight_loss'] },

  // ── CROCK POT / INSTANT POT ─────────────────────────────────────────────
  { id: 'crock-pulled-chicken', name: 'Crock pot pulled chicken (4 breasts + jar of salsa, 6hr low)', emoji: '🍲', playbook: 'crock_pot', when: 'dinner', phase: 1, ingredients: ['4 chicken breasts', 'jar of salsa', 'crock pot'], prepMinutes: 5, cost: 2, protein_g: 35, targets: ['high_protein', 'satiety'], constraint: { maxPrepMinutes: 15 } },
  { id: 'crock-chili', name: 'Crock pot chili (1lb beef + 2 cans tomatoes + 2 cans beans + chili powder)', emoji: '🌶️', playbook: 'crock_pot', when: 'dinner', phase: 1, ingredients: ['1 lb ground beef', '2 cans diced tomatoes', '2 cans kidney beans', 'chili powder', 'cumin', 'crock pot'], prepMinutes: 10, cost: 1, protein_g: 30, targets: ['high_protein', 'high_fiber', 'satiety'], constraint: { maxPrepMinutes: 15 } },
  { id: 'crock-italian-sausage-soup', name: 'Crock pot Italian sausage soup (sausage + frozen mirepoix + chicken broth + cannellini beans + frozen kale)', emoji: '🍲', playbook: 'crock_pot', when: 'dinner', phase: 1, ingredients: ['Italian sausage', 'frozen mirepoix', 'chicken broth', 'cannellini beans', 'frozen kale', 'crock pot'], prepMinutes: 10, cost: 2, protein_g: 28, targets: ['high_protein', 'high_fiber', 'anti_inflammatory'], constraint: { maxPrepMinutes: 15 } },
  { id: 'crock-honey-garlic-thighs', name: 'Crock pot honey-garlic chicken thighs (10 thighs + soy + honey + garlic + ginger)', emoji: '🍗', playbook: 'crock_pot', when: 'dinner', phase: 1, ingredients: ['10 chicken thighs', 'soy sauce', 'honey', 'garlic', 'ginger', 'crock pot'], prepMinutes: 10, cost: 2, protein_g: 32, targets: ['high_protein', 'satiety', 'low_test'], constraint: { maxPrepMinutes: 15 } },
  { id: 'instant-pot-whole-chicken', name: 'Instant Pot whole chicken (40 min start to finish, $5)', emoji: '🍗', playbook: 'crock_pot', when: 'dinner', phase: 2, ingredients: ['whole chicken', 'salt', 'pepper', 'garlic powder', 'Instant Pot'], prepMinutes: 5, cost: 1, protein_g: 40, targets: ['high_protein', 'satiety'] },
  { id: 'crock-beef-broccoli', name: 'Crock pot beef + broccoli (chuck + soy + brown sugar + frozen broccoli)', emoji: '🥦', playbook: 'crock_pot', when: 'dinner', phase: 1, ingredients: ['chuck roast', 'soy sauce', 'brown sugar', 'frozen broccoli', 'crock pot'], prepMinutes: 10, cost: 2, protein_g: 35, targets: ['high_protein', 'low_carb'], constraint: { maxPrepMinutes: 15 } },
  { id: 'crock-turkey-breast', name: 'Crock pot turkey breast (Sunday roast → 4 days of sandwich filling)', emoji: '🦃', playbook: 'crock_pot', when: 'dinner', phase: 2, ingredients: ['turkey breast', 'olive oil', 'rosemary', 'salt', 'crock pot'], prepMinutes: 10, cost: 2, protein_g: 40, targets: ['high_protein', 'satiety'] },
  { id: 'crock-pulled-pork', name: 'Crock pot pulled pork (pork shoulder + bottle of BBQ, 8hr low)', emoji: '🍖', playbook: 'crock_pot', when: 'dinner', phase: 1, ingredients: ['pork shoulder', 'bottle BBQ sauce', 'crock pot'], prepMinutes: 5, cost: 2, protein_g: 30, targets: ['high_protein', 'satiety'], constraint: { hasKids: true } },
  { id: 'crock-bolognese-banza', name: 'Crock pot bolognese over Banza pasta (sauce + ground beef + Italian seasoning)', emoji: '🍝', playbook: 'crock_pot', when: 'dinner', phase: 2, ingredients: ['ground beef', 'jar marinara', 'Italian seasoning', 'Banza chickpea pasta', 'crock pot'], prepMinutes: 10, cost: 2, protein_g: 40, targets: ['high_protein', 'high_fiber'], constraint: { hasKids: true, maxPrepMinutes: 15 } },

  // ── SHEET-PAN / ONE-PAN ─────────────────────────────────────────────────
  { id: 'sheet-chicken-thighs-sweet-potato', name: 'Sheet-pan chicken thighs + sweet potato cubes + frozen peppers (425°F, 25min)', emoji: '🥘', playbook: 'sheet_pan', when: 'dinner', phase: 2, ingredients: ['chicken thighs', 'sweet potato cubes', 'frozen pepper-onion mix', 'olive oil', 'salt', 'sheet pan'], prepMinutes: 5, cost: 2, protein_g: 35, targets: ['high_protein', 'high_fiber', 'satiety'] },
  { id: 'sheet-sausage-peppers', name: 'Sheet-pan sausage + frozen pre-sliced peppers + onions (one tray, 20min)', emoji: '🌶️', playbook: 'sheet_pan', when: 'dinner', phase: 1, ingredients: ['Italian sausage links', 'frozen pepper-onion mix', 'olive oil', 'sheet pan'], prepMinutes: 5, cost: 2, protein_g: 28, targets: ['high_protein', 'low_carb'] },
  { id: 'skillet-egg-roll-bowl', name: 'One-skillet egg roll in a bowl (ground turkey + bagged coleslaw + soy + ginger, 12 min)', emoji: '🥡', playbook: 'sheet_pan', when: 'dinner', phase: 1, ingredients: ['ground turkey', 'bagged coleslaw', 'soy sauce', 'ginger', 'sesame oil', 'skillet'], prepMinutes: 12, cost: 2, protein_g: 32, targets: ['high_protein', 'low_carb'], constraint: { maxPrepMinutes: 15 } },
  { id: 'skillet-ground-beef-rice', name: 'One-pan ground beef + Minute Rice + frozen broccoli (15 min)', emoji: '🥩', playbook: 'sheet_pan', when: 'dinner', phase: 1, ingredients: ['ground beef', 'Minute Rice', 'frozen broccoli', 'soy sauce', 'skillet'], prepMinutes: 15, cost: 1, protein_g: 35, targets: ['high_protein'], constraint: { maxPrepMinutes: 15 } },
  { id: 'skillet-chicken-fajitas', name: 'One-skillet chicken fajitas (sliced chicken + frozen pepper-onion mix + taco seasoning, 12 min)', emoji: '🌯', playbook: 'sheet_pan', when: 'dinner', phase: 1, ingredients: ['sliced chicken breast', 'frozen pepper-onion mix', 'taco seasoning', 'tortillas (optional)', 'skillet'], prepMinutes: 12, cost: 2, protein_g: 38, targets: ['high_protein', 'satiety'], constraint: { maxPrepMinutes: 15 } },
  { id: 'sheet-kielbasa-brussels', name: 'Sheet-pan kielbasa + Brussels sprouts + frozen sweet potato fries (425°F, 25min)', emoji: '🥘', playbook: 'sheet_pan', when: 'dinner', phase: 2, ingredients: ['kielbasa', 'Brussels sprouts', 'frozen sweet potato fries', 'olive oil', 'sheet pan'], prepMinutes: 10, cost: 2, protein_g: 25, targets: ['high_protein', 'high_fiber'] },
  { id: 'sheet-salmon-asparagus-tomato', name: 'Sheet-pan salmon + asparagus + cherry tomatoes (15 min, 400°F)', emoji: '🐟', playbook: 'sheet_pan', when: 'dinner', phase: 2, ingredients: ['salmon fillet', 'asparagus', 'cherry tomatoes', 'olive oil', 'lemon', 'sheet pan'], prepMinutes: 15, cost: 2, protein_g: 35, targets: ['high_protein', 'omega3', 'high_tg'], constraint: { excludeDiet: ['vegan', 'vegetarian'] } },

  // ── FROZEN AISLE WINS ───────────────────────────────────────────────────
  { id: 'costco-salmon-burger', name: 'Costco frozen salmon burger on brioche bun + sliced avocado + side salad (4 min air-fryer)', emoji: '🐟', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['Costco frozen salmon burger', 'brioche bun', 'sliced avocado', 'bagged side salad', 'air fryer'], prepMinutes: 5, cost: 2, protein_g: 30, targets: ['high_protein', 'omega3', 'high_tg'], constraint: { excludeDiet: ['vegan', 'vegetarian'] } },
  { id: 'tj-grilled-chicken-strips', name: 'Trader Joe\'s frozen grilled chicken strips + bagged Caesar kit (60-sec microwave)', emoji: '🥗', playbook: 'frozen_aisle', when: 'lunch', phase: 1, ingredients: ['TJ\'s frozen grilled chicken strips', 'bagged Caesar kit'], prepMinutes: 3, cost: 2, protein_g: 35, targets: ['high_protein', 'low_carb'] },
  { id: 'tj-orange-chicken-broccoli', name: 'Trader Joe\'s frozen orange chicken + frozen broccoli', emoji: '🥡', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['TJ\'s frozen orange chicken', 'frozen broccoli'], prepMinutes: 10, cost: 2, protein_g: 25, targets: ['high_protein'] },
  { id: 'tj-cauli-pesto-shrimp', name: 'Trader Joe\'s frozen riced cauliflower + jarred pesto + frozen shrimp', emoji: '🍤', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['TJ\'s frozen riced cauliflower', 'jarred pesto', 'frozen shrimp'], prepMinutes: 10, cost: 2, protein_g: 28, targets: ['high_protein', 'low_carb', 'omega3'] },
  { id: 'aldi-protein-pizza', name: 'Aldi Mama Cozzi protein crust pizza (frozen, 15 min)', emoji: '🍕', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['Aldi Mama Cozzi protein pizza'], prepMinutes: 15, cost: 1, protein_g: 30, targets: ['high_protein', 'satiety'], constraint: { hasKids: true } },
  { id: 'banza-marinara-meatballs', name: 'Banza chickpea pasta + Rao\'s marinara + frozen meatballs', emoji: '🍝', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['Banza chickpea pasta', 'Rao\'s marinara', 'frozen meatballs'], prepMinutes: 15, cost: 2, protein_g: 40, targets: ['high_protein', 'high_fiber'], constraint: { hasKids: true } },
  { id: 'costco-meatballs-marinara', name: 'Costco frozen meatballs + Rao\'s marinara over Banza pasta', emoji: '🥘', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['Costco frozen meatballs', 'Rao\'s marinara', 'Banza pasta'], prepMinutes: 15, cost: 2, protein_g: 38, targets: ['high_protein'] },
  { id: 'costco-korean-bbq-bowl', name: 'Costco frozen Korean BBQ beef bowl (microwave 4 min)', emoji: '🍚', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['Costco Korean BBQ beef bowl'], prepMinutes: 5, cost: 2, protein_g: 28, targets: ['high_protein'] },
  { id: 'birds-eye-veggie-bag', name: 'Birds Eye Steamfresh veggie bag + leftover protein (3 min microwave)', emoji: '🥦', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['Birds Eye Steamfresh veggie bag', 'leftover protein'], prepMinutes: 5, cost: 1, protein_g: 25, targets: ['high_fiber', 'satiety'] },
  { id: 'aunt-millie-frozen-toast-stack', name: 'Frozen Aunt Millie\'s protein bread + Boar\'s Head turkey + cheese (toaster)', emoji: '🥪', playbook: 'frozen_aisle', when: 'lunch', phase: 1, ingredients: ['Aunt Millie\'s protein bread (frozen)', 'Boar\'s Head turkey', 'cheese'], prepMinutes: 5, cost: 2, protein_g: 28, targets: ['high_protein'] },

  // ── FROZEN BREAKFAST SANDWICHES ─────────────────────────────────────────
  { id: 'jimmy-dean-delights', name: 'Jimmy Dean Delights turkey sausage frozen sandwich + Premier shake', emoji: '🥪', playbook: 'frozen_breakfast', when: 'breakfast', phase: 1, ingredients: ['Jimmy Dean Delights turkey sausage sandwich', 'Premier Protein shake'], prepMinutes: 2, cost: 2, protein_g: 47, targets: ['high_protein', 'energy_steady'] },
  { id: 'make-ahead-egg-muffin-tin', name: 'Make-ahead egg muffin tin (Sunday batch: 12 eggs + spinach + ham + cheese)', emoji: '🧁', playbook: 'frozen_breakfast', when: 'breakfast', phase: 2, ingredients: ['12 eggs', 'spinach', 'diced ham', 'cheese', 'muffin tin'], prepMinutes: 30, cost: 1, protein_g: 18, targets: ['high_protein', 'low_folate'], constraint: { maxPrepMinutes: 60 } },
  { id: 'eggwich-sandwich', name: 'Eggwich frozen sandwiches (egg-white buns with cheese filling)', emoji: '🥚', playbook: 'frozen_breakfast', when: 'breakfast', phase: 1, ingredients: ['Eggwich frozen sandwich'], prepMinutes: 2, cost: 1, protein_g: 14, targets: ['high_protein', 'low_carb'] },
  { id: 'tattooed-chef-burrito', name: 'Tattooed Chef frozen breakfast burrito + black coffee', emoji: '🌯', playbook: 'frozen_breakfast', when: 'breakfast', phase: 1, ingredients: ['Tattooed Chef frozen breakfast burrito', 'black coffee'], prepMinutes: 3, cost: 2, protein_g: 18, targets: ['high_protein'] },
  { id: 'kirkland-frozen-breakfast-bowl', name: 'Costco Kirkland frozen breakfast bowl', emoji: '🍳', playbook: 'frozen_breakfast', when: 'breakfast', phase: 1, ingredients: ['Kirkland frozen breakfast bowl'], prepMinutes: 4, cost: 1, protein_g: 22, targets: ['high_protein'] },
  { id: 'kodiak-waffles-pb-banana', name: 'Frozen Kodiak protein waffles + peanut butter + banana', emoji: '🧇', playbook: 'frozen_breakfast', when: 'breakfast', phase: 1, ingredients: ['Kodiak frozen waffles', 'peanut butter', 'banana'], prepMinutes: 4, cost: 2, protein_g: 20, targets: ['high_protein', 'energy_steady'] },

  // ── LOW-CAL DRINKS ──────────────────────────────────────────────────────
  { id: 'protein-iced-coffee', name: 'Premier Protein iced coffee (shake + cold brew + ice in shaker)', emoji: '☕', playbook: 'low_cal_drink', when: 'breakfast', phase: 1, ingredients: ['Premier Protein shake', 'cold brew coffee', 'ice'], prepMinutes: 2, cost: 1, protein_g: 30, targets: ['high_protein', 'energy_steady'] },
  { id: 'collagen-coffee', name: 'Black coffee + scoop of unflavored collagen + cinnamon', emoji: '☕', playbook: 'low_cal_drink', when: 'breakfast', phase: 1, ingredients: ['black coffee', 'unflavored collagen', 'cinnamon'], prepMinutes: 1, cost: 1, protein_g: 10, targets: ['high_protein'] },
  { id: 'lmnt-sparkling', name: 'Sparkling water + LMNT or Liquid IV zero stick', emoji: '💧', playbook: 'low_cal_drink', when: 'snack', phase: 1, ingredients: ['sparkling water', 'LMNT or Liquid IV zero stick'], prepMinutes: 1, cost: 1, targets: ['energy_steady'] },
  { id: 'acv-shot-pre-meal', name: 'Apple cider vinegar shot pre-meal (Bragg\'s, 1 tbsp in water + ice)', emoji: '🥤', playbook: 'low_cal_drink', when: 'snack', phase: 1, ingredients: ['Bragg\'s ACV', 'water', 'ice'], prepMinutes: 1, cost: 1, targets: ['high_glucose', 'insulin_resistance'] },
  { id: 'sleepy-girl-mocktail', name: 'Sleepy girl mocktail (tart cherry juice + magnesium glycinate powder + sparkling water)', emoji: '🍒', playbook: 'low_cal_drink', when: 'snack', phase: 1, ingredients: ['tart cherry juice', 'magnesium glycinate powder', 'sparkling water'], prepMinutes: 2, cost: 1, targets: ['sleep_support', 'cortisol_calm'] },
  { id: 'olipop-soda', name: 'Olipop or Poppi prebiotic soda (replaces Coke)', emoji: '🥤', playbook: 'low_cal_drink', when: 'snack', phase: 1, ingredients: ['Olipop or Poppi prebiotic soda'], prepMinutes: 0, cost: 1, targets: ['gut_inflammation', 'high_fiber'] },
  { id: 'fairlife-post-workout', name: 'Fairlife Core Power post-workout shake', emoji: '🥛', playbook: 'low_cal_drink', when: 'snack', phase: 1, ingredients: ['Fairlife Core Power'], prepMinutes: 0, cost: 1, protein_g: 26, targets: ['muscle_gain', 'high_protein'] },
  { id: 'iced-matcha-almond', name: 'Iced matcha (Trader Joe\'s matcha + almond milk + ice)', emoji: '🍵', playbook: 'low_cal_drink', when: 'breakfast', phase: 1, ingredients: ['TJ\'s matcha powder', 'unsweetened almond milk', 'ice'], prepMinutes: 2, cost: 1, targets: ['cortisol_calm', 'anti_inflammatory'] },
  { id: 'athletic-greens', name: 'Athletic Greens or Bloom Greens + cold water', emoji: '🥬', playbook: 'low_cal_drink', when: 'breakfast', phase: 1, ingredients: ['Athletic Greens or Bloom Greens powder', 'cold water'], prepMinutes: 1, cost: 2, targets: ['anti_inflammatory', 'high_fiber'] },

  // ── MOM / PARENT FRIENDLY ───────────────────────────────────────────────
  { id: 'banza-marinara-meatballs-family', name: 'Banza chickpea pasta + Rao\'s marinara + Costco meatballs (family meal)', emoji: '🍝', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['Banza chickpea pasta', 'Rao\'s marinara', 'Costco frozen meatballs'], prepMinutes: 15, cost: 2, protein_g: 38, targets: ['high_protein', 'high_fiber'], constraint: { hasKids: true } },
  { id: 'rotisserie-stouffer-split', name: 'Costco rotisserie chicken + Stouffer\'s mac (kid eats mac, adult eats chicken + Caesar)', emoji: '🍗', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['Costco rotisserie chicken', 'Stouffer\'s mac & cheese', 'bagged Caesar kit'], prepMinutes: 10, cost: 2, protein_g: 40, targets: ['high_protein'], constraint: { hasKids: true } },
  { id: 'sheet-pan-flatbread-pizza', name: 'Sheet-pan pizza on Aunt Millie\'s flatbread (kid customizes toppings)', emoji: '🍕', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['Aunt Millie\'s flatbread', 'pizza sauce', 'cheese', 'toppings of choice'], prepMinutes: 15, cost: 2, protein_g: 22, targets: ['satiety'], constraint: { hasKids: true } },
  { id: 'crock-pulled-chicken-tacos', name: 'Crock pot pulled chicken tacos (kid uses tortillas, adult bowls it over greens)', emoji: '🌮', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['crock pot pulled chicken', 'tortillas', 'salsa', 'greens (for adult bowl)', 'cheese'], prepMinutes: 10, cost: 2, protein_g: 30, targets: ['high_protein'], constraint: { hasKids: true } },
  { id: 'rotisserie-quesadilla-mission', name: 'Costco rotisserie quesadilla on Mission carb-balance tortilla', emoji: '🫓', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['Costco rotisserie chicken', 'Mission carb balance tortilla', 'cheese'], prepMinutes: 10, cost: 1, protein_g: 32, targets: ['high_protein', 'low_carb'], constraint: { hasKids: true } },
  { id: 'build-your-own-bowls-night', name: 'Build-your-own bowls (rice + Costco rotisserie + frozen peppers + salsa + cheese)', emoji: '🍚', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['rice', 'Costco rotisserie chicken', 'frozen peppers', 'salsa', 'cheese'], prepMinutes: 15, cost: 2, protein_g: 35, targets: ['high_protein'], constraint: { hasKids: true } },
  { id: 'banza-vodka-broccoli', name: 'Banza pasta + Rao\'s vodka sauce + frozen broccoli (15 min)', emoji: '🍝', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['Banza chickpea pasta', 'Rao\'s vodka sauce', 'frozen broccoli'], prepMinutes: 15, cost: 2, protein_g: 28, targets: ['high_protein', 'high_fiber'], constraint: { hasKids: true, maxPrepMinutes: 30 } },

  // ── VIRAL TIKTOK HACKS ──────────────────────────────────────────────────
  { id: 'cottage-cheese-ice-cream', name: 'Cottage cheese "ice cream" (cottage cheese + PB + sugar-free chocolate, blended)', emoji: '🍦', playbook: 'viral_hack', when: 'snack', phase: 1, ingredients: ['cottage cheese', 'peanut butter', 'sugar-free chocolate syrup', 'NutriBullet'], prepMinutes: 5, cost: 1, protein_g: 28, targets: ['high_protein', 'weight_loss', 'satiety'] },
  { id: 'greek-yogurt-bark', name: 'Greek yogurt bark (yogurt + honey + berries, frozen flat, broken into shards)', emoji: '🍓', playbook: 'viral_hack', when: 'snack', phase: 1, ingredients: ['Greek yogurt', 'honey', 'berries', 'parchment paper'], prepMinutes: 10, cost: 1, protein_g: 18, targets: ['high_protein', 'satiety'] },
  { id: 'frozen-banana-bites', name: 'Chocolate-covered frozen banana bites (banana coins + dark chocolate)', emoji: '🍫', playbook: 'viral_hack', when: 'snack', phase: 1, ingredients: ['banana', 'dark chocolate', 'freezer'], prepMinutes: 10, cost: 1, targets: ['weight_loss', 'satiety'] },
  { id: 'chia-pudding-overnight', name: 'Chia pudding overnight (chia + almond milk + scoop protein powder)', emoji: '🥣', playbook: 'viral_hack', when: 'breakfast', phase: 1, ingredients: ['chia seeds', 'almond milk', 'protein powder'], prepMinutes: 5, cost: 1, protein_g: 22, targets: ['high_protein', 'high_fiber', 'omega3'] },
  { id: 'cottage-cheese-cucumber', name: 'Cottage cheese + everything bagel seasoning + sliced cucumber', emoji: '🥒', playbook: 'viral_hack', when: 'snack', phase: 1, ingredients: ['cottage cheese', 'everything bagel seasoning', 'cucumber slices'], prepMinutes: 3, cost: 1, protein_g: 28, targets: ['high_protein', 'low_carb'] },
  { id: 'dense-bean-salad', name: 'Dense bean salad (canned beans + chopped veg + lemon + olive oil, fridges 5 days)', emoji: '🫘', playbook: 'viral_hack', when: 'lunch', phase: 1, ingredients: ['canned beans (chickpea + black)', 'cucumber', 'tomato', 'red onion', 'lemon', 'olive oil'], prepMinutes: 15, cost: 1, protein_g: 18, targets: ['high_fiber', 'high_protein', 'anti_inflammatory'] },
  { id: 'cottage-cheese-chips', name: 'Cottage cheese chips (microwave-bake at 350°F = high-protein chip)', emoji: '🥨', playbook: 'viral_hack', when: 'snack', phase: 2, ingredients: ['cottage cheese', 'parchment'], prepMinutes: 15, cost: 1, protein_g: 25, targets: ['high_protein', 'low_carb'] },
  { id: 'whipped-cottage-cheese', name: 'Whipped cottage cheese spread on Aunt Millie\'s toast + everything bagel seasoning', emoji: '🥯', playbook: 'viral_hack', when: 'breakfast', phase: 1, ingredients: ['cottage cheese (food-processed)', 'Aunt Millie\'s toast', 'everything bagel seasoning'], prepMinutes: 5, cost: 1, protein_g: 24, targets: ['high_protein'] },
  { id: 'rotisserie-chicken-salad', name: 'Costco rotisserie chicken salad (shred + Greek yogurt + grapes + celery)', emoji: '🥗', playbook: 'viral_hack', when: 'lunch', phase: 1, ingredients: ['Costco rotisserie chicken (shredded)', 'Greek yogurt', 'grapes', 'celery'], prepMinutes: 10, cost: 2, protein_g: 35, targets: ['high_protein', 'satiety'] },

  // ── LUNCHBOX / THERMOS ──────────────────────────────────────────────────
  { id: 'thermos-leftover-chili', name: 'Thermos chili (8-hour hot hold, leftover crock pot chili)', emoji: '🌶️', playbook: 'lunchbox_thermos', when: 'lunch', phase: 1, ingredients: ['leftover crock pot chili', 'thermos'], prepMinutes: 2, cost: 1, protein_g: 30, targets: ['high_protein', 'satiety'], constraint: { workType: ['driver', 'shift', 'labor', 'service'] } },
  { id: 'pyrex-cooler-box', name: 'Pyrex cooler box (pre-cooked chicken + Minute Rice cup + cucumber + ranch)', emoji: '🍱', playbook: 'lunchbox_thermos', when: 'lunch', phase: 1, ingredients: ['pre-cooked chicken', 'Minute Rice cup', 'cucumber slices', 'ranch packet', 'Pyrex'], prepMinutes: 5, cost: 2, protein_g: 35, targets: ['high_protein'], constraint: { workType: ['driver', 'shift', 'labor', 'service'] } },
  { id: 'dashboard-protein-combo', name: 'Dashboard combo: turkey jerky + Premier Protein + apple + string cheese', emoji: '🚛', playbook: 'lunchbox_thermos', when: 'lunch', phase: 1, ingredients: ['turkey jerky', 'Premier Protein shake', 'apple', 'string cheese'], prepMinutes: 0, cost: 2, protein_g: 45, targets: ['high_protein', 'satiety'], constraint: { workType: ['driver'] } },
  { id: 'construction-lunchbox', name: 'Construction lunchbox: 4 hard-boiled eggs + 2 string cheese + apple + Quest bar', emoji: '🔨', playbook: 'lunchbox_thermos', when: 'lunch', phase: 1, ingredients: ['4× hard-boiled eggs', '2× string cheese', 'apple', 'Quest bar'], prepMinutes: 0, cost: 1, protein_g: 45, targets: ['high_protein', 'satiety'], constraint: { workType: ['labor', 'service'] } },
  { id: 'thermos-lentil-soup', name: 'Driver thermos: lentil soup OR Instant Pot beef stew (hot 8 hrs)', emoji: '🍲', playbook: 'lunchbox_thermos', when: 'lunch', phase: 2, ingredients: ['lentil soup or beef stew (leftover)', 'thermos'], prepMinutes: 2, cost: 1, protein_g: 25, targets: ['high_fiber', 'high_protein'], constraint: { workType: ['driver', 'shift'] } },
  { id: 'cold-cooler-steak-rice', name: 'Cold cooler combo: leftover steak + microwave rice + cherry tomatoes + ranch', emoji: '🥩', playbook: 'lunchbox_thermos', when: 'lunch', phase: 2, ingredients: ['leftover steak', 'microwave rice', 'cherry tomatoes', 'ranch'], prepMinutes: 5, cost: 2, protein_g: 35, targets: ['high_protein'], constraint: { workType: ['driver', 'shift', 'labor'] } },
  { id: 'trucker-special-eggs-cheese', name: 'Trucker special: 2× hard-boiled eggs + 2× Babybel + Premier shake + bag of almonds', emoji: '🥚', playbook: 'lunchbox_thermos', when: 'lunch', phase: 1, ingredients: ['2× hard-boiled eggs', '2× Babybel cheese', 'Premier Protein shake', 'almonds'], prepMinutes: 0, cost: 2, protein_g: 50, targets: ['high_protein', 'satiety'], constraint: { workType: ['driver'] } },
  { id: 'shift-overnight-roast-beef', name: 'Shift-worker overnight box: cold roast beef + spinach wrap + cheese cubes + apple', emoji: '🌙', playbook: 'lunchbox_thermos', when: 'lunch', phase: 1, ingredients: ['cold roast beef', 'spinach wrap', 'cheese cubes', 'apple'], prepMinutes: 5, cost: 2, protein_g: 38, targets: ['high_protein'], constraint: { workType: ['shift'] } },

  // ── SIMPLE HOME COOK (Phase 3) ──────────────────────────────────────────
  { id: 'home-salmon-power-bowl', name: 'Salmon power bowl (Costco frozen filet + brown rice + bagged kale slaw + avocado + sriracha + sesame oil)', emoji: '🐟', playbook: 'simple_home_cook', when: 'dinner', phase: 3, ingredients: ['Costco frozen salmon filet', 'brown rice', 'bagged kale slaw', 'avocado', 'sriracha', 'sesame oil'], prepMinutes: 20, cost: 2, protein_g: 42, targets: ['high_protein', 'omega3', 'high_tg'], constraint: { excludeDiet: ['vegan', 'vegetarian'] } },
  { id: 'home-chicken-thighs-brussels', name: 'Chicken thighs + roasted Brussels sprouts + brown rice + lemon', emoji: '🍗', playbook: 'simple_home_cook', when: 'dinner', phase: 3, ingredients: ['chicken thighs', 'Brussels sprouts', 'brown rice', 'lemon', 'olive oil'], prepMinutes: 25, cost: 2, protein_g: 40, targets: ['high_protein', 'high_fiber'] },
  { id: 'home-steak-fajitas', name: 'Steak fajita night (sliced flank + frozen pepper-onion mix + tortillas)', emoji: '🌯', playbook: 'simple_home_cook', when: 'dinner', phase: 3, ingredients: ['flank steak', 'frozen pepper-onion mix', 'tortillas', 'lime', 'cilantro'], prepMinutes: 20, cost: 2, protein_g: 40, targets: ['high_protein', 'low_test'] },
  { id: 'home-greek-bowl', name: 'Greek bowl: ground turkey + cucumber + tomato + tzatziki + brown rice + feta', emoji: '🥙', playbook: 'simple_home_cook', when: 'dinner', phase: 3, ingredients: ['ground turkey', 'cucumber', 'tomato', 'tzatziki', 'brown rice', 'feta'], prepMinutes: 20, cost: 2, protein_g: 38, targets: ['high_protein', 'high_fiber'] },
  { id: 'home-chicken-parm-banza', name: 'Chicken parmesan night (pounded chicken + jar marinara + Banza pasta + mozzarella)', emoji: '🍝', playbook: 'simple_home_cook', when: 'dinner', phase: 3, ingredients: ['pounded chicken breast', 'jar marinara', 'Banza pasta', 'mozzarella'], prepMinutes: 25, cost: 2, protein_g: 50, targets: ['high_protein'] },
  { id: 'home-beef-stew-dutch', name: 'Beef stew (chuck + onion + carrot + potato + canned tomatoes, Dutch oven 2 hrs)', emoji: '🍲', playbook: 'simple_home_cook', when: 'dinner', phase: 3, ingredients: ['chuck roast', 'onion', 'carrot', 'potato', 'canned tomatoes', 'Dutch oven'], prepMinutes: 20, cost: 2, protein_g: 35, targets: ['high_protein', 'high_fiber'] },
  { id: 'home-korean-bbq-bowl', name: 'Korean BBQ bowl (ground beef + soy + brown sugar + rice + frozen broccoli + kimchi)', emoji: '🍚', playbook: 'simple_home_cook', when: 'dinner', phase: 3, ingredients: ['ground beef', 'soy sauce', 'brown sugar', 'rice', 'frozen broccoli', 'kimchi'], prepMinutes: 20, cost: 2, protein_g: 38, targets: ['high_protein', 'gut_inflammation'] },

  // ─────────────────────────────────────────────────────────────────────
  // EXPANSION SET 2 — 60+ new meals (no fries, no hash browns, no regular
  // soda; zero-sugar drinks fine)
  // ─────────────────────────────────────────────────────────────────────

  // ── More CONVENIENCE STORE ──────────────────────────────────────────
  { id: 'royal-farms-chicken-tenders', name: 'Royal Farms 4-pc fried chicken tenders + side salad (skip the fries — get extra tender)', emoji: '🍗', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Royal Farms 4-pc chicken tenders', 'side salad', 'water or Diet Coke'], prepMinutes: 0, cost: 2, protein_g: 35, targets: ['high_protein'], constraint: { requiresChain: ['Royal Farms'] } },
  { id: 'qt-grilled-chicken-flatbread', name: 'QuikTrip grilled chicken flatbread + apple slices + bottled water', emoji: '🌯', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['QuikTrip grilled chicken flatbread', 'apple slices', 'water'], prepMinutes: 0, cost: 2, protein_g: 28, targets: ['high_protein'], constraint: { requiresChain: ['QuikTrip'] } },
  { id: 'caseys-hot-deli-rotisserie', name: 'Casey\'s hot deli rotisserie chicken thigh + 2 hard-boiled eggs + apple', emoji: '🍗', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Casey\'s rotisserie chicken thigh', '2× hard-boiled eggs', 'apple'], prepMinutes: 0, cost: 2, protein_g: 38, targets: ['high_protein'], constraint: { requiresChain: ['Casey\'s'] } },
  { id: 'wawa-buffalo-bowl-light', name: 'Wawa buffalo chicken Bowl with greens base instead of grain', emoji: '🥬', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Wawa buffalo chicken bowl', 'greens base', 'water'], prepMinutes: 0, cost: 2, protein_g: 30, targets: ['high_protein', 'low_carb'], constraint: { requiresChain: ['Wawa'] } },
  { id: '7eleven-jerky-protein-bar-water', name: '7-Eleven jerky stick + Quest bar + bottled water (truck-stop classic)', emoji: '🥩', playbook: 'convenience_store', when: 'snack', phase: 1, ingredients: ['7-Eleven beef jerky stick', 'Quest bar', 'bottled water'], prepMinutes: 0, cost: 1, protein_g: 30, targets: ['high_protein'], constraint: { requiresChain: ['7-Eleven'], workType: ['driver', 'shift', 'labor'] } },
  { id: 'sheetz-grilled-chicken-cobb', name: 'Sheetz Made-To-Order grilled chicken Cobb salad + unsweet iced tea', emoji: '🥗', playbook: 'convenience_store', when: 'lunch', phase: 1, ingredients: ['Sheetz grilled chicken Cobb salad', 'unsweet iced tea'], prepMinutes: 0, cost: 2, protein_g: 35, targets: ['high_protein', 'low_carb'], constraint: { requiresChain: ['Sheetz'] } },
  { id: 'pilot-loves-egg-bites', name: 'Pilot/Love\'s grab-and-go egg bites + 2 string cheese + apple', emoji: '🥚', playbook: 'convenience_store', when: 'breakfast', phase: 1, ingredients: ['hot-case egg bites', '2× string cheese', 'apple'], prepMinutes: 0, cost: 1, protein_g: 28, targets: ['high_protein'], constraint: { workType: ['driver', 'shift'] } },

  // ── More FAST-FOOD (chain rotation) ─────────────────────────────────
  { id: 'cfa-cool-wrap', name: 'Chick-fil-A Cool Wrap (grilled chicken, lettuce, cheddar) + Diet Lemonade', emoji: '🌯', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Chick-fil-A Cool Wrap', 'Diet Lemonade'], prepMinutes: 0, cost: 2, protein_g: 38, targets: ['high_protein'], constraint: { requiresChain: ['Chick-fil-A'] } },
  { id: 'cfa-grilled-cobb-salad', name: 'Chick-fil-A Grilled Cobb Salad + apple slices + water', emoji: '🥗', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Chick-fil-A Grilled Cobb Salad', 'apple slices', 'water'], prepMinutes: 0, cost: 2, protein_g: 40, targets: ['high_protein', 'low_carb'], constraint: { requiresChain: ['Chick-fil-A'] } },
  { id: 'wendys-grilled-chicken-wrap', name: 'Wendy\'s grilled chicken wrap + side salad + Diet Coke', emoji: '🌯', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Wendy\'s grilled chicken wrap', 'side salad', 'Diet Coke'], prepMinutes: 0, cost: 2, protein_g: 28, targets: ['high_protein'], constraint: { requiresChain: ['Wendy\'s'] } },
  { id: 'wendys-double-stack-no-cheese', name: 'Wendy\'s Jr. Bacon Cheeseburger + side salad + Diet Coke (skip fries)', emoji: '🍔', playbook: 'fast_food', when: 'lunch', phase: 2, ingredients: ['Wendy\'s Jr. Bacon Cheeseburger', 'side salad', 'Diet Coke'], prepMinutes: 0, cost: 2, protein_g: 22, targets: ['satiety'], constraint: { requiresChain: ['Wendy\'s'] } },
  { id: 'mcd-double-cheeseburger-water', name: 'McDonald\'s double cheeseburger (no fries) + side salad + water', emoji: '🍔', playbook: 'fast_food', when: 'lunch', phase: 2, ingredients: ['McDonald\'s double cheeseburger', 'side salad', 'water'], prepMinutes: 0, cost: 1, protein_g: 22, targets: ['satiety'], constraint: { requiresChain: ["McDonald's"] } },
  { id: 'mcd-bacon-egg-cheese-biscuit-no-hb', name: 'McDonald\'s bacon, egg & cheese biscuit (no hash brown) + black coffee', emoji: '🥪', playbook: 'fast_food', when: 'breakfast', phase: 1, ingredients: ['McDonald\'s bacon egg cheese biscuit', 'black coffee'], prepMinutes: 0, cost: 1, protein_g: 17, targets: ['high_protein'], constraint: { requiresChain: ["McDonald's"] } },
  { id: 'subway-italian-bmt-protein', name: 'Subway Italian B.M.T. on flatbread (double meat, all veggies) + apple', emoji: '🥖', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Subway Italian B.M.T.', 'flatbread', 'double meat', 'all veggies', 'apple'], prepMinutes: 0, cost: 2, protein_g: 40, targets: ['high_protein'], constraint: { requiresChain: ['Subway'] } },
  { id: 'subway-rotisserie-salad', name: 'Subway Rotisserie chicken chopped salad + Diet Coke', emoji: '🥗', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Subway rotisserie chicken chopped salad', 'Diet Coke'], prepMinutes: 0, cost: 2, protein_g: 32, targets: ['high_protein', 'low_carb'], constraint: { requiresChain: ['Subway'] } },
  { id: 'dunkin-egg-white-veggie', name: 'Dunkin egg white & veggie wake-up wrap (×2) + black coffee', emoji: '🌯', playbook: 'fast_food', when: 'breakfast', phase: 1, ingredients: ['2× Dunkin egg white veggie wake-up wrap', 'black coffee'], prepMinutes: 0, cost: 2, protein_g: 22, targets: ['high_protein'], constraint: { requiresChain: ['Dunkin'] } },
  { id: 'dunkin-power-breakfast-sandwich', name: 'Dunkin power breakfast sandwich (egg white + turkey sausage) + cold brew', emoji: '🥪', playbook: 'fast_food', when: 'breakfast', phase: 1, ingredients: ['Dunkin power breakfast sandwich', 'cold brew (no sugar)'], prepMinutes: 0, cost: 2, protein_g: 25, targets: ['high_protein'], constraint: { requiresChain: ['Dunkin'] } },
  { id: 'starbucks-egg-bites-bacon', name: 'Starbucks bacon & gruyère egg bites + cold brew + banana', emoji: '🥚', playbook: 'fast_food', when: 'breakfast', phase: 1, ingredients: ['Starbucks bacon gruyère egg bites', 'cold brew', 'banana'], prepMinutes: 0, cost: 2, protein_g: 19, targets: ['high_protein'], constraint: { requiresChain: ['Starbucks'] } },
  { id: 'starbucks-egg-white-bites', name: 'Starbucks egg white red pepper bites + iced black coffee', emoji: '🥚', playbook: 'fast_food', when: 'breakfast', phase: 1, ingredients: ['Starbucks egg white red pepper bites', 'iced black coffee'], prepMinutes: 0, cost: 2, protein_g: 13, targets: ['high_protein'], constraint: { requiresChain: ['Starbucks'] } },
  { id: 'panera-greek-bowl', name: 'Panera Mediterranean Bowl with chicken (no pita) + sparkling water', emoji: '🥗', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Panera Mediterranean Bowl with chicken', 'sparkling water'], prepMinutes: 0, cost: 2, protein_g: 35, targets: ['high_protein', 'high_fiber'], constraint: { requiresChain: ['Panera'] } },
  { id: 'taco-bell-fresco-chicken-soft', name: 'Taco Bell fresco-style chicken soft tacos (×3) + side of black beans', emoji: '🌮', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['3× Taco Bell fresco chicken soft taco', 'side black beans'], prepMinutes: 0, cost: 1, protein_g: 30, targets: ['high_protein'], constraint: { requiresChain: ['Taco Bell'] } },
  { id: 'taco-bell-cantina-chicken-bowl', name: 'Taco Bell Cantina chicken bowl (no rice if low-carb day) + Diet Coke', emoji: '🥣', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Taco Bell Cantina chicken bowl', 'Diet Coke'], prepMinutes: 0, cost: 1, protein_g: 28, targets: ['high_protein'], constraint: { requiresChain: ['Taco Bell'] } },
  { id: 'jersey-mikes-jersey-shore', name: 'Jersey Mike\'s #7 Jersey Shore Favorite (no mayo OR yes mayo, your call) on wheat', emoji: '🥖', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Jersey Mike\'s #7 sub on wheat', 'lettuce', 'tomato', 'onion'], prepMinutes: 0, cost: 2, protein_g: 32, targets: ['high_protein'], constraint: { requiresChain: ['Jersey Mike'] } },
  { id: 'jimmy-johns-tuna-club', name: 'Jimmy John\'s tuna unwich (lettuce wrap) + chips of choice — your call', emoji: '🥬', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Jimmy John\'s tuna unwich', 'water'], prepMinutes: 0, cost: 2, protein_g: 25, targets: ['high_protein', 'low_carb'], constraint: { requiresChain: ['Jimmy John'] } },
  { id: 'arbys-roast-beef-no-fries', name: 'Arby\'s roast beef (regular) + side salad + Diet Coke (skip the curly fries)', emoji: '🥪', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Arby\'s roast beef sandwich', 'side salad', 'Diet Coke'], prepMinutes: 0, cost: 1, protein_g: 22, targets: ['high_protein'], constraint: { requiresChain: ['Arby'] } },
  { id: 'popeyes-blackened-chicken-sandwich', name: 'Popeyes blackened chicken sandwich (not fried) + side green beans', emoji: '🌶️', playbook: 'fast_food', when: 'lunch', phase: 1, ingredients: ['Popeyes blackened chicken sandwich', 'green beans'], prepMinutes: 0, cost: 2, protein_g: 32, targets: ['high_protein'], constraint: { requiresChain: ['Popeyes'] } },
  { id: 'kfc-grilled-chicken-greens', name: 'KFC grilled chicken (2pc) + green beans + corn on the cob', emoji: '🍗', playbook: 'fast_food', when: 'dinner', phase: 1, ingredients: ['KFC grilled chicken 2pc', 'green beans', 'corn on the cob'], prepMinutes: 0, cost: 2, protein_g: 38, targets: ['high_protein'], constraint: { requiresChain: ['KFC'] } },

  // ── More PROTEIN BARS / SHAKES ──────────────────────────────────────
  { id: 'fairlife-shake-banana', name: 'Fairlife Core Power shake (vanilla) + banana + handful of walnuts', emoji: '🥛', playbook: 'protein_bar_shake', when: 'breakfast', phase: 1, ingredients: ['Fairlife Core Power shake', 'banana', 'walnuts'], prepMinutes: 0, cost: 2, protein_g: 30, targets: ['high_protein', 'omega3'] },
  { id: 'kirkland-shake-handful-almonds', name: 'Costco Kirkland protein shake + small handful of almonds', emoji: '🥛', playbook: 'protein_bar_shake', when: 'breakfast', phase: 1, ingredients: ['Kirkland protein shake', 'almonds'], prepMinutes: 0, cost: 1, protein_g: 35, targets: ['high_protein'] },
  { id: 'no-cow-bar-coffee', name: 'No Cow protein bar (vegan-friendly) + black coffee', emoji: '🍫', playbook: 'protein_bar_shake', when: 'snack', phase: 1, ingredients: ['No Cow protein bar', 'black coffee'], prepMinutes: 0, cost: 1, protein_g: 21, targets: ['high_protein'], constraint: { diet: ['vegan', 'plant_based', 'standard'] } },
  { id: 'rxbar-banana-water', name: 'RXBAR + banana + bottled water', emoji: '🍫', playbook: 'protein_bar_shake', when: 'snack', phase: 1, ingredients: ['RXBAR', 'banana', 'water'], prepMinutes: 0, cost: 1, protein_g: 12, targets: ['satiety'] },
  { id: 'orgain-shake-fruit', name: 'Orgain organic protein shake + apple slices', emoji: '🥛', playbook: 'protein_bar_shake', when: 'snack', phase: 1, ingredients: ['Orgain organic protein shake', 'apple slices'], prepMinutes: 0, cost: 2, protein_g: 21, targets: ['high_protein'] },

  // ── More CROCK POT ──────────────────────────────────────────────────
  { id: 'crock-salsa-verde-pork', name: 'Crock pot salsa verde pork (pork shoulder + jar salsa verde, 8hr) + brown rice', emoji: '🌶️', playbook: 'crock_pot', when: 'dinner', phase: 1, ingredients: ['pork shoulder', 'jar salsa verde', 'brown rice', 'crock pot'], prepMinutes: 5, cost: 2, protein_g: 30, targets: ['high_protein'] },
  { id: 'crock-buffalo-chicken', name: 'Crock pot buffalo chicken (4 breasts + bottle Frank\'s + ranch packet, 6hr)', emoji: '🌶️', playbook: 'crock_pot', when: 'dinner', phase: 1, ingredients: ['4 chicken breasts', 'Frank\'s RedHot', 'ranch seasoning packet', 'crock pot'], prepMinutes: 5, cost: 2, protein_g: 32, targets: ['high_protein'] },
  { id: 'crock-chicken-tikka', name: 'Crock pot chicken tikka masala (chicken thighs + jar Patak\'s sauce + frozen cauliflower rice)', emoji: '🍛', playbook: 'crock_pot', when: 'dinner', phase: 2, ingredients: ['chicken thighs', 'jar Patak\'s tikka masala sauce', 'frozen cauliflower rice', 'crock pot'], prepMinutes: 10, cost: 2, protein_g: 35, targets: ['high_protein'] },
  { id: 'crock-mississippi-pot-roast', name: 'Crock pot Mississippi pot roast (chuck + au jus + ranch + pepperoncini, 8hr)', emoji: '🥩', playbook: 'crock_pot', when: 'dinner', phase: 2, ingredients: ['chuck roast', 'au jus mix', 'ranch packet', 'pepperoncini', 'crock pot'], prepMinutes: 5, cost: 2, protein_g: 38, targets: ['high_protein', 'satiety'] },
  { id: 'crock-chicken-noodle-banza', name: 'Crock pot chicken noodle soup over Banza pasta (chicken + carrots + celery + broth)', emoji: '🍲', playbook: 'crock_pot', when: 'dinner', phase: 1, ingredients: ['chicken breasts', 'baby carrots', 'celery', 'chicken broth', 'Banza pasta', 'crock pot'], prepMinutes: 10, cost: 1, protein_g: 30, targets: ['high_protein', 'high_fiber'] },

  // ── More SHEET PAN ──────────────────────────────────────────────────
  { id: 'sheet-shrimp-broccoli-stir', name: 'Sheet-pan honey-garlic shrimp + frozen broccoli + brown rice (15min)', emoji: '🍤', playbook: 'sheet_pan', when: 'dinner', phase: 2, ingredients: ['frozen shrimp', 'frozen broccoli', 'brown rice', 'soy sauce', 'honey', 'garlic', 'sheet pan'], prepMinutes: 15, cost: 2, protein_g: 30, targets: ['high_protein', 'omega3'] },
  { id: 'one-skillet-meatballs-marinara', name: 'One-skillet frozen meatballs + Rao\'s marinara + zoodles', emoji: '🍝', playbook: 'sheet_pan', when: 'dinner', phase: 1, ingredients: ['Costco frozen meatballs', 'Rao\'s marinara', 'frozen zoodles', 'skillet'], prepMinutes: 12, cost: 2, protein_g: 32, targets: ['high_protein', 'low_carb'] },
  { id: 'sheet-chicken-thighs-fajita', name: 'Sheet-pan chicken thighs + frozen fajita veggies + tortillas (425°F, 25min)', emoji: '🌯', playbook: 'sheet_pan', when: 'dinner', phase: 1, ingredients: ['chicken thighs', 'frozen fajita pepper-onion mix', 'tortillas', 'olive oil', 'sheet pan'], prepMinutes: 10, cost: 2, protein_g: 35, targets: ['high_protein'] },
  { id: 'one-pot-jambalaya-instant', name: 'One-pot Cajun jambalaya (instant rice + andouille + frozen peppers + Cajun seasoning)', emoji: '🌶️', playbook: 'sheet_pan', when: 'dinner', phase: 2, ingredients: ['Minute rice', 'andouille sausage', 'frozen pepper-onion mix', 'Cajun seasoning', 'one pot'], prepMinutes: 15, cost: 2, protein_g: 28, targets: ['high_protein'] },

  // ── More FROZEN AISLE ───────────────────────────────────────────────
  { id: 'tj-mandarin-orange-bowl', name: 'Trader Joe\'s mandarin orange chicken + frozen riced cauliflower (lighter swap)', emoji: '🍊', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['TJ\'s frozen mandarin orange chicken', 'frozen riced cauliflower'], prepMinutes: 10, cost: 2, protein_g: 22, targets: ['high_protein', 'low_carb'] },
  { id: 'aldi-fitness-bowl-grilled-chicken', name: 'Aldi fitness bowl: frozen grilled chicken + frozen broccoli + microwave brown rice', emoji: '🥗', playbook: 'frozen_aisle', when: 'lunch', phase: 1, ingredients: ['Aldi frozen grilled chicken', 'frozen broccoli', 'microwave brown rice'], prepMinutes: 8, cost: 1, protein_g: 35, targets: ['high_protein'] },
  { id: 'amys-organic-burrito', name: 'Amy\'s organic frozen burrito + sliced avocado + side salad', emoji: '🌯', playbook: 'frozen_aisle', when: 'lunch', phase: 1, ingredients: ['Amy\'s organic frozen burrito', 'sliced avocado', 'side salad'], prepMinutes: 5, cost: 2, protein_g: 18, targets: ['high_fiber'], constraint: { diet: ['vegan', 'plant_based', 'vegetarian', 'standard'] } },
  { id: 'tj-cauliflower-gnocchi-pesto', name: 'Trader Joe\'s frozen cauliflower gnocchi + jarred pesto + frozen meatballs', emoji: '🍝', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['TJ\'s cauliflower gnocchi', 'jarred pesto', 'frozen meatballs'], prepMinutes: 12, cost: 2, protein_g: 28, targets: ['high_protein'] },
  { id: 'tj-frozen-shrimp-stir-fry', name: 'Trader Joe\'s frozen shrimp + frozen stir-fry veggie blend + soy sauce', emoji: '🍤', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['TJ\'s frozen shrimp', 'frozen stir-fry veggies', 'soy sauce'], prepMinutes: 10, cost: 2, protein_g: 28, targets: ['high_protein', 'omega3', 'low_carb'] },
  { id: 'costco-chicken-pot-pie-side-salad', name: 'Costco frozen chicken pot pie (eat half) + bagged side salad', emoji: '🥧', playbook: 'frozen_aisle', when: 'dinner', phase: 1, ingredients: ['Costco frozen chicken pot pie (half)', 'bagged side salad'], prepMinutes: 25, cost: 2, protein_g: 22, targets: ['satiety'] },
  { id: 'evol-power-bowl', name: 'Evol Power Bowl (cilantro lime chicken) + sliced cucumber', emoji: '🥣', playbook: 'frozen_aisle', when: 'lunch', phase: 1, ingredients: ['Evol Power Bowl cilantro lime chicken', 'cucumber slices'], prepMinutes: 5, cost: 2, protein_g: 25, targets: ['high_protein'] },

  // ── More FROZEN BREAKFAST ───────────────────────────────────────────
  { id: 'costco-breakfast-sandwich-bowl', name: 'Costco bagel breakfast sandwich + side of berries', emoji: '🥯', playbook: 'frozen_breakfast', when: 'breakfast', phase: 1, ingredients: ['Costco bagel breakfast sandwich (frozen)', 'mixed berries'], prepMinutes: 3, cost: 2, protein_g: 22, targets: ['high_protein'] },
  { id: 'jimmy-dean-egg-white-bowl', name: 'Jimmy Dean turkey sausage egg white frozen bowl + black coffee', emoji: '🥣', playbook: 'frozen_breakfast', when: 'breakfast', phase: 1, ingredients: ['Jimmy Dean turkey sausage egg white bowl (frozen)', 'black coffee'], prepMinutes: 3, cost: 2, protein_g: 25, targets: ['high_protein'] },
  { id: 'birds-eye-protein-bowl', name: 'Birds Eye Voila! frozen breakfast skillet + black coffee', emoji: '🍳', playbook: 'frozen_breakfast', when: 'breakfast', phase: 1, ingredients: ['Birds Eye Voila breakfast skillet (frozen)', 'black coffee'], prepMinutes: 6, cost: 2, protein_g: 18, targets: ['high_protein'] },

  // ── More LOW-CAL DRINKS ─────────────────────────────────────────────
  { id: 'diet-coke-with-lunch', name: 'Diet Coke or Coke Zero (zero sugar, pair with any meal)', emoji: '🥤', playbook: 'low_cal_drink', when: 'snack', phase: 1, ingredients: ['Diet Coke or Coke Zero'], prepMinutes: 0, cost: 1, targets: ['weight_loss'] },
  { id: 'unsweet-iced-tea', name: 'Unsweetened iced tea + lemon (replaces sweet tea / soda)', emoji: '🍵', playbook: 'low_cal_drink', when: 'snack', phase: 1, ingredients: ['unsweetened iced tea', 'lemon wedge', 'ice'], prepMinutes: 1, cost: 1, targets: ['weight_loss'] },
  { id: 'celsius-pre-workout', name: 'Celsius zero-sugar energy drink + handful of almonds (pre-workout)', emoji: '⚡', playbook: 'low_cal_drink', when: 'snack', phase: 1, ingredients: ['Celsius zero sugar', 'almonds'], prepMinutes: 0, cost: 1, protein_g: 6, targets: ['energy_steady'] },
  { id: 'oatzempic-hack', name: 'Oatzempic-style breakfast drink (oats + lime + water, blended) + protein scoop', emoji: '🥤', playbook: 'low_cal_drink', when: 'breakfast', phase: 1, ingredients: ['1/2 cup oats', '1 lime', '1 cup water', 'scoop protein powder', 'blender'], prepMinutes: 3, cost: 1, protein_g: 25, targets: ['high_fiber', 'high_protein', 'weight_loss'] },
  { id: 'iced-protein-coffee-blender', name: 'Blender iced protein coffee (whey + cold brew + ice + dash cinnamon)', emoji: '☕', playbook: 'low_cal_drink', when: 'breakfast', phase: 1, ingredients: ['1 scoop whey vanilla', 'cold brew coffee', 'ice', 'cinnamon', 'blender'], prepMinutes: 2, cost: 1, protein_g: 25, targets: ['high_protein', 'energy_steady'] },

  // ── More VIRAL HACKS ────────────────────────────────────────────────
  { id: 'cottage-cheese-pizza-bowl', name: 'Cottage cheese pizza bowl (cottage cheese + Rao\'s marinara + mozzarella + Italian seasoning, microwave 60s)', emoji: '🍕', playbook: 'viral_hack', when: 'snack', phase: 1, ingredients: ['cottage cheese', 'Rao\'s marinara', 'shredded mozzarella', 'Italian seasoning'], prepMinutes: 3, cost: 1, protein_g: 30, targets: ['high_protein', 'low_carb'] },
  { id: 'cottage-cheese-banana-blender', name: 'Cottage cheese banana blender muffins (TikTok 4-ingredient hack)', emoji: '🧁', playbook: 'viral_hack', when: 'breakfast', phase: 2, ingredients: ['cottage cheese', 'banana', 'rolled oats', 'eggs', 'blender + muffin tin'], prepMinutes: 25, cost: 1, protein_g: 18, targets: ['high_protein', 'high_fiber'] },
  { id: 'protein-french-toast', name: 'High-protein French toast (Aunt Millie\'s + cottage cheese batter)', emoji: '🍞', playbook: 'viral_hack', when: 'breakfast', phase: 1, ingredients: ['Aunt Millie\'s protein bread', 'cottage cheese', 'eggs', 'cinnamon', 'sugar-free maple syrup'], prepMinutes: 8, cost: 1, protein_g: 35, targets: ['high_protein'] },
  { id: 'ground-beef-rice-cake', name: 'Ground beef rice cake stack (ground beef + rice cake + everything seasoning + Greek yogurt)', emoji: '🍙', playbook: 'viral_hack', when: 'lunch', phase: 1, ingredients: ['ground beef (cooked)', 'rice cake', 'everything seasoning', 'Greek yogurt'], prepMinutes: 8, cost: 1, protein_g: 30, targets: ['high_protein'] },
  { id: 'tuna-cucumber-stack', name: 'Tuna cucumber stack (canned tuna + Greek yogurt + cucumber slice base)', emoji: '🐟', playbook: 'viral_hack', when: 'snack', phase: 1, ingredients: ['canned tuna', 'Greek yogurt', 'cucumber slices', 'everything seasoning'], prepMinutes: 5, cost: 1, protein_g: 28, targets: ['high_protein', 'low_carb'] },
  { id: 'sleepy-magnesium-banana', name: 'Sleepy banana (banana + 2 tbsp peanut butter + magnesium powder, before bed)', emoji: '🌙', playbook: 'viral_hack', when: 'snack', phase: 1, ingredients: ['banana', 'peanut butter', 'magnesium glycinate powder'], prepMinutes: 2, cost: 1, targets: ['sleep_support'] },

  // ── More LUNCHBOX / THERMOS ─────────────────────────────────────────
  { id: 'thermos-broccoli-cheddar-soup', name: 'Thermos broccoli cheddar soup (Panera at Costco or homemade) + grilled chicken on top', emoji: '🥣', playbook: 'lunchbox_thermos', when: 'lunch', phase: 2, ingredients: ['Panera broccoli cheddar soup (Costco frozen)', 'grilled chicken strips', 'thermos'], prepMinutes: 5, cost: 2, protein_g: 30, targets: ['high_protein'], constraint: { workType: ['driver', 'shift', 'labor'] } },
  { id: 'mason-jar-salad-prep', name: 'Mason-jar salad meal prep (5 jars: dressing bottom, chicken, beans, greens top)', emoji: '🥗', playbook: 'lunchbox_thermos', when: 'lunch', phase: 2, ingredients: ['mason jars', 'olive oil + balsamic', 'rotisserie chicken', 'canned chickpeas', 'mixed greens'], prepMinutes: 30, cost: 2, protein_g: 30, targets: ['high_protein', 'high_fiber'] },
  { id: 'pyrex-burrito-bowl-prep', name: 'Pyrex burrito bowl prep (rotisserie chicken + rice + black beans + salsa, 4 portions)', emoji: '🍚', playbook: 'lunchbox_thermos', when: 'lunch', phase: 1, ingredients: ['rotisserie chicken', 'microwave rice', 'canned black beans', 'salsa', 'Pyrex containers'], prepMinutes: 15, cost: 2, protein_g: 35, targets: ['high_protein'] },
  { id: 'cooler-tuna-mayo-pita', name: 'Cooler-pack tuna mayo + pita crackers + cherry tomatoes + apple', emoji: '🐟', playbook: 'lunchbox_thermos', when: 'lunch', phase: 1, ingredients: ['canned tuna with mayo', 'whole-wheat pita crackers', 'cherry tomatoes', 'apple'], prepMinutes: 5, cost: 1, protein_g: 28, targets: ['high_protein', 'omega3'], constraint: { workType: ['driver', 'shift', 'labor'] } },

  // ── More MOM-FRIENDLY ───────────────────────────────────────────────
  { id: 'sheet-pan-quesadillas', name: 'Sheet-pan quesadillas (Mission tortillas + rotisserie chicken + cheese) — kid + adult', emoji: '🫓', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['Mission tortillas', 'rotisserie chicken', 'shredded cheese', 'salsa', 'sheet pan'], prepMinutes: 12, cost: 2, protein_g: 30, targets: ['high_protein'], constraint: { hasKids: true } },
  { id: 'taco-tuesday-build-your-own', name: 'Taco Tuesday: ground beef + Mission tortillas + cheese + salsa (kid customizes)', emoji: '🌮', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['ground beef (cooked)', 'Mission tortillas', 'shredded cheese', 'salsa', 'lettuce'], prepMinutes: 15, cost: 1, protein_g: 30, targets: ['high_protein'], constraint: { hasKids: true } },
  { id: 'breakfast-for-dinner-eggs', name: 'Breakfast-for-dinner: scrambled eggs + Aunt Millie\'s toast + turkey bacon (kids love this)', emoji: '🍳', playbook: 'mom_friendly', when: 'dinner', phase: 1, ingredients: ['eggs', 'Aunt Millie\'s protein bread', 'turkey bacon'], prepMinutes: 10, cost: 1, protein_g: 28, targets: ['high_protein'], constraint: { hasKids: true } },

  // ── More SIMPLE HOME COOK ───────────────────────────────────────────
  { id: 'home-air-fryer-salmon-veggies', name: 'Air-fryer salmon + frozen broccoli + Minute brown rice (12min total)', emoji: '🐟', playbook: 'simple_home_cook', when: 'dinner', phase: 2, ingredients: ['fresh salmon filet', 'frozen broccoli', 'Minute brown rice', 'olive oil', 'lemon', 'air fryer'], prepMinutes: 12, cost: 2, protein_g: 38, targets: ['high_protein', 'omega3', 'high_tg'], constraint: { excludeDiet: ['vegan', 'vegetarian'] } },
  { id: 'home-instant-pot-chili', name: 'Instant Pot chili (1lb beef + 2 cans tomatoes + 2 cans beans + 25 min pressure)', emoji: '🌶️', playbook: 'simple_home_cook', when: 'dinner', phase: 2, ingredients: ['ground beef', 'canned tomatoes', 'canned beans', 'chili powder', 'Instant Pot'], prepMinutes: 25, cost: 1, protein_g: 32, targets: ['high_protein', 'high_fiber'] },
  { id: 'home-pesto-shrimp-zoodles', name: 'Pesto shrimp zoodles (frozen shrimp + jarred pesto + frozen zoodles, 10 min)', emoji: '🍝', playbook: 'simple_home_cook', when: 'dinner', phase: 2, ingredients: ['frozen shrimp', 'jarred pesto', 'frozen zoodles', 'parmesan'], prepMinutes: 10, cost: 2, protein_g: 32, targets: ['high_protein', 'low_carb'], constraint: { excludeDiet: ['vegan'] } },
];

// Quick stats for sanity
export const PLAYBOOK_COUNT = FOOD_PLAYBOOK.reduce((acc, m) => {
  acc[m.playbook] = (acc[m.playbook] ?? 0) + 1;
  return acc;
}, {} as Record<Playbook, number>);
