// src/pages/legal/Disclaimer.tsx
import { LandingNav } from '../../components/landing/LandingNav';
import { LandingFooter } from '../../components/landing/LandingFooter';

export const Disclaimer = () => (
  <div className="min-h-screen bg-clinical-cream">
    <LandingNav />
    <main className="max-w-3xl mx-auto px-6 py-24 md:py-32">
      <p className="text-precision text-[0.68rem] font-bold tracking-widest uppercase text-primary-container mb-3">Legal</p>
      <h1 className="text-authority text-4xl md:text-5xl text-clinical-charcoal font-bold mb-6 leading-tight">Medical Disclaimer</h1>
      <p className="text-body text-clinical-stone text-base mb-10">Last updated: May 6, 2026</p>

      <div className="prose prose-lg max-w-none space-y-6">
        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">Educational use only</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            CauseHealth is an educational health intelligence platform. Everything you see — lab
            interpretations, supplement suggestions, doctor prep documents, wellness plans, AI
            chat replies — is for <strong>informational purposes only</strong>. None of it
            constitutes medical advice, diagnosis, or treatment. CauseHealth is not a substitute
            for evaluation by a licensed healthcare provider.
          </p>
        </section>

        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">CauseHealth is not HIPAA-covered</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            <strong>HIPAA does not apply to CauseHealth.</strong> The Health Insurance Portability
            and Accountability Act regulates healthcare providers, health plans, and their business
            associates. CauseHealth is a consumer health information service that you voluntarily
            upload your own data to — it is none of those things and does not bill insurance.
          </p>
          <p className="text-body text-clinical-charcoal leading-relaxed mt-3">
            The privacy and security of your data on CauseHealth are protected by our Privacy
            Policy, the FTC Health Breach Notification Rule, the California Consumer Privacy Act
            (CCPA), the EU General Data Protection Regulation (GDPR), and the Washington My Health
            My Data Act — not by HIPAA. If you require HIPAA-covered handling, keep that
            information in your healthcare provider's HIPAA-covered systems instead.
          </p>
        </section>

        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">Always talk to your doctor</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            Discuss every finding, supplement change, medication adjustment, or dietary
            intervention with your physician <strong>before making any change</strong>. Your
            doctor knows your full medical history, medications, allergies, and individual risk
            factors that an AI tool cannot fully account for.
          </p>
        </section>

        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">Lab value interpretation</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            CauseHealth uses functional medicine optimal-range thresholds in addition to standard
            laboratory reference ranges. These optimal ranges are tighter than what most clinical
            labs flag as "out of range" and are not universally accepted by all medical bodies.
            A value flagged as "monitor" or "urgent" by CauseHealth may still be within your lab's
            "normal" range. <strong>Use the flags as conversation starters with your doctor, not
            as diagnoses.</strong>
          </p>
        </section>

        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">AI limitations</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            Our analyses are generated by large language models with built-in clinical guardrails.
            They can be wrong, inconsistent, or miss nuances a trained clinician would catch.
            Cross-reference any major decision with your healthcare team. Never delay seeking
            medical care because of something CauseHealth told you.
          </p>
        </section>

        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">Supplement and medication safety</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            Many supplements interact with prescription medications, alter lab values, or are
            contraindicated in specific conditions (pregnancy, kidney disease, anticoagulant use,
            etc.). Always check with a qualified pharmacist or physician before starting any new
            supplement, especially if you take prescription medications.
          </p>
        </section>

        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">Emergency situations</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            <strong>If you are having a medical emergency, call 911 or go to your nearest
            emergency room immediately.</strong> Do not use CauseHealth for emergency triage. We
            are not staffed to respond to acute medical situations.
          </p>
        </section>

        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">No clinician-patient relationship</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            Use of CauseHealth does not create a doctor-patient relationship. We do not employ
            licensed physicians to review individual results. The "doctor prep" documents we
            generate are designed as discussion aids for visits with <em>your</em> doctor — not
            as replacement consultations.
          </p>
        </section>

        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">FDA + regulatory status</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            CauseHealth has not been evaluated by the U.S. Food and Drug Administration. We are
            not a medical device. Statements about supplements, lifestyle interventions, or lab
            interpretations have not been reviewed by the FDA and are not intended to diagnose,
            treat, cure, or prevent any disease.
          </p>
        </section>

        <section>
          <h2 className="text-authority text-2xl text-clinical-charcoal font-bold mb-3">Questions</h2>
          <p className="text-body text-clinical-charcoal leading-relaxed">
            Reach us at <a href="mailto:support@causehealth.app" className="text-primary-container underline">support@causehealth.app</a> with any
            concerns about how to interpret findings or use the platform safely.
          </p>
        </section>
      </div>
    </main>
    <LandingFooter />
  </div>
);
