// src/pages/legal/Privacy.tsx
import { LandingNav } from '../../components/landing/LandingNav';
import { LandingFooter } from '../../components/landing/LandingFooter';

export const Privacy = () => (
  <div className="min-h-screen bg-clinical-cream">
    <LandingNav />
    <div className="max-w-3xl mx-auto px-6 pt-32 pb-20">
      <h1 className="text-authority text-4xl text-clinical-charcoal font-bold mb-2">Privacy Policy</h1>
      <p className="text-body text-clinical-stone mb-10">Last updated: April 9, 2026</p>

      <div className="prose prose-sm max-w-none space-y-8">
        <Section title="1. Overview">
          CauseHealth takes your privacy seriously. This policy explains what data we collect, how we use it, how we protect it, and your rights regarding your data. We never sell your personal information or health data to anyone, for any reason.
        </Section>

        <Section title="2. What Data We Collect">
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li><strong>Account information:</strong> Email address, name, date of birth, biological sex, height, weight — provided during registration and onboarding.</li>
            <li><strong>Health information:</strong> Lab results (uploaded as PDFs), medications, diagnosed conditions, symptoms and severity ratings, lifestyle data — provided by you during onboarding and app usage.</li>
            <li><strong>Generated content:</strong> Wellness plans, doctor prep documents, symptom analyses, and lab interpretations generated by AI from your data.</li>
            <li><strong>Usage data:</strong> Anonymous feature usage patterns (which screens you visit, what you click).</li>
            <li><strong>Payment information:</strong> Processed securely by Stripe. We do not store your credit card number, CVV, or billing details on our servers.</li>
          </ul>
        </Section>

        <Section title="3. How We Use Your Data">
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li><strong>To provide the service:</strong> Your health data is used to generate personalized lab analysis, wellness plans, doctor prep documents, and symptom insights.</li>
            <li><strong>AI processing:</strong> Your lab values, medications, symptoms, and conditions are sent to Anthropic's Claude AI API to generate analysis and recommendations. This data is sent securely via encrypted connection (HTTPS/TLS). Anthropic does not use your data to train their models.</li>
            <li><strong>To improve the service:</strong> We may use aggregated, de-identified data to improve our algorithms and features. Individual health records are never used for this purpose.</li>
            <li><strong>To communicate with you:</strong> Account updates, subscription changes, and service announcements.</li>
          </ul>
        </Section>

        <Section title="4. How We Protect Your Data">
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li><strong>Encryption:</strong> All data is encrypted in transit (TLS 1.2+) and at rest (AES-256) via our infrastructure provider, Supabase.</li>
            <li><strong>Access control:</strong> Row-Level Security (RLS) ensures you can only access your own data. No other user can see your information.</li>
            <li><strong>Authentication:</strong> Secure session management with automatic token refresh and JWT verification on all API calls.</li>
            <li><strong>Infrastructure:</strong> Data is stored on Supabase (built on AWS), which maintains SOC 2 Type II compliance.</li>
            <li><strong>No employee access:</strong> CauseHealth staff do not access individual user health records unless explicitly requested by you for support purposes.</li>
          </ul>
        </Section>

        <Section title="5. Third-Party Services">
          <table className="w-full text-sm mt-2">
            <thead>
              <tr className="border-b border-outline-variant/20">
                <th className="text-left py-2 text-clinical-charcoal font-semibold">Service</th>
                <th className="text-left py-2 text-clinical-charcoal font-semibold">Purpose</th>
                <th className="text-left py-2 text-clinical-charcoal font-semibold">Data Shared</th>
              </tr>
            </thead>
            <tbody className="text-clinical-stone">
              <tr className="border-b border-outline-variant/10">
                <td className="py-2">Supabase</td>
                <td className="py-2">Database, authentication, file storage</td>
                <td className="py-2">All account and health data (encrypted)</td>
              </tr>
              <tr className="border-b border-outline-variant/10">
                <td className="py-2">Anthropic (Claude AI)</td>
                <td className="py-2">AI-powered health analysis</td>
                <td className="py-2">Lab values, medications, symptoms, conditions (for analysis only — not used for AI training)</td>
              </tr>
              <tr className="border-b border-outline-variant/10">
                <td className="py-2">Stripe</td>
                <td className="py-2">Payment processing</td>
                <td className="py-2">Email, name, payment method (handled entirely by Stripe)</td>
              </tr>
              <tr>
                <td className="py-2">Vercel</td>
                <td className="py-2">Website hosting</td>
                <td className="py-2">No health data — static file serving only</td>
              </tr>
            </tbody>
          </table>
        </Section>

        <Section title="6. HIPAA Disclosure">
          CauseHealth is a <strong>health education tool</strong>, not a covered entity under HIPAA. We do not provide medical care, treatment, or payment processing for healthcare services. While we implement strong security practices (encryption, access control, audit logging), we do not claim HIPAA compliance. If you require HIPAA-compliant health data storage, please consult your healthcare provider's patient portal.
        </Section>

        <Section title="7. Your Rights">
          <ul className="list-disc pl-5 space-y-2 mt-2">
            <li><strong>Access:</strong> You can view all your data within the app at any time.</li>
            <li><strong>Export:</strong> You can export all your data as JSON from Settings → Your Data.</li>
            <li><strong>Delete:</strong> You can permanently delete your account and all associated data from Settings → Your Data. Deletion is immediate and irreversible.</li>
            <li><strong>Correct:</strong> You can update your profile, medications, conditions, and symptoms at any time through Settings → Health Profile.</li>
            <li><strong>Withdraw consent:</strong> You can stop using the service at any time. Deleting your account removes all data.</li>
          </ul>
        </Section>

        <Section title="8. Data Retention">
          We retain your data for as long as your account is active. When you delete your account, all data is permanently removed from our database within 30 days (including backups). We do not retain health data after account deletion. Stripe may retain payment records per their own retention policy for legal and tax compliance.
        </Section>

        <Section title="9. Children's Privacy">
          CauseHealth is not intended for use by individuals under 18 years of age. We do not knowingly collect data from minors. If we discover that a user is under 18, we will delete their account and data promptly.
        </Section>

        <Section title="10. California Residents (CCPA)">
          If you are a California resident, you have the right to: know what personal information we collect, request deletion of your data, and opt out of data sales. We do not sell personal information. To exercise these rights, contact us at the email below or use the in-app data management tools.
        </Section>

        <Section title="11. Changes to This Policy">
          We may update this privacy policy from time to time. We will notify you of material changes via email or in-app notification. Continued use after changes constitutes acceptance.
        </Section>

        <Section title="12. Contact">
          For privacy questions or data requests, contact us at <a href="mailto:privacy@causehealth.app" className="text-primary-container hover:underline">privacy@causehealth.app</a>.
        </Section>
      </div>
    </div>
    <LandingFooter />
  </div>
);

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div>
    <h2 className="text-authority text-xl text-clinical-charcoal font-semibold mb-3">{title}</h2>
    <div className="text-body text-clinical-stone text-sm leading-relaxed">{children}</div>
  </div>
);
